services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
  
  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev -- --host

  database:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: