FROM node:20-alpine

WORKDIR /usr/src/app

# Copier les fichiers package.json et pnpm-lock.yaml
COPY package*.json pnpm-lock.yaml ./

# Installer pnpm globalement
RUN npm install -g pnpm

# Installer les dépendances
RUN pnpm install --prod --frozen-lockfile

COPY . .

# Variable d'environnement pour la production
ENV NODE_ENV=production

# Le port sera défini par Render
ENV PORT=10000

EXPOSE $PORT

CMD ["node", "app.js"]