FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --only=production

COPY . .

# Variable d'environnement pour la production
ENV NODE_ENV=production

# Le port sera défini par Render
ENV PORT=10000

EXPOSE $PORT

CMD ["node", "app.js"]